### PR TITLE
Include notice about Fable support

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Will this do?

### CODE REVIEW

**Comment by forki** [comment]
Hugs

**Comment by forki** [comment]
image

^^ the link you sent doesn't really work for me. The map seems broken

**Comment by Zaid-Ajaj** [comment]
It is not broken, I am using by default the free open street maps server to load map tiles (region images) and it has a certain rate limit when many people use the tiles. Just refresh the page after a minute or so and you will see the tiles. There is already an [open issue](https://github.com/Zaid-Ajaj/Feliz/issues/59) to allow pigeon maps to use different tile servers

**Comment by forki** [comment]
Ah OK. Thank you

Zaid Ajaj <notifications@github.com> schrieb am Mi., 4. März 2020, 13:19:

**Pull request merged**
